FROM node:20-slim AS build
WORKDIR /app

ARG GOOGLE_MAP_KEY
ARG GO_PORT
ARG AUTH_PORT
ARG REACT_PORT

ENV GOOGLE_MAP_KEY=$GOOGLE_MAP_KEY
ENV GO_PORT=$GO_PORT
ENV AUTH_PORT=$AUTH_PORT
ENV REACT_PORT=$REACT_PORT

COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]